name: pandora-paper
channels:
  - conda-forge
  - bioconda
  - nodefaults
dependencies:
  - notebook
  - pandas
  - numpy
  - scipy
  - pyreadr
  - pyyaml
  - fastparquet
  - snakemake
  - scikit-learn
  - scikit-allel
  - stdpopsim
  - pingouin
  - plotly
  - pandora-geno
  - eigensoft
