name: pandora-paper
channels:
  - conda-forge
  - bioconda
  - nodefaults
dependencies:
  - notebook
  - pandas
  - numpy
  - scipy
  - pyreadr
  - fastparquet
  - snakemake
  - pandora-geno
  - scikit-learn
  - scikit-allel
  - stdpopsim
