dataset_prefix: /Users/julia/Desktop/Promotion/ADNA_Popgen/Pandora/tests/data/example
dataset_format: EIGENSTRAT

outdir_base: /tmp/results

smartpca_optional_settings:
  numoutlieriter: 0

threads: 8